#!/bin/bash

#Customize this for your application
APPLICATION_FILE_PATH=Glimmr

#Parameters
PRODUCT_HOME=/Library/__PRODUCT__

echo "Post installation process started..."

#Change permissions in home directory
echo "Changing permissions in product home..."
cd ${PRODUCT_HOME}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

echo "Adding shortcut to /usr/local/bin..."
#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/__PRODUCT__-__VERSION__
cp ${PRODUCT_HOME}/com.glimmr.loginscript.plist ~/Library/LaunchAgents/com.glimmr.loginscript.plist
launchctl load ~/Library/LaunchAgents/com.glimmr.loginscript.plist
ln -s ${PRODUCT_HOME}/${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
echo "Main post installation process finished."

echo "Checking Homebrew..."
which -s brew
if [[ $? != 0 ]] ; then
  echo "Installing homebrew..."
  # Install Homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Updating homebrew..."
  brew update
fi

echo "Installing dependencies..."
brew install gtk+3 hdf5 lapack
export LDFLAGS="-L/usr/local/opt/lapack/lib"
export CPPFLAGS="-I/usr/local/opt/lapack/include"
brew install jasper
brew tap cartr/qt4 && brew install qt@4
brew install mesa libdc1394 tesseract
brew install icu4c brew link icu4c --force
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
brew install jpeg libpng libtiff libav ffmpeg gcc glfw3 glew opencv unzip libtiff libgeotiff gstreamer gst-plugins-base gst-plugins-good openexr eigen
brew install --cask cmake
brew install freeglut libusb
brew install zlib
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"

echo "Post installation process finished"
